package co.edu.uniquindio.proyecto.modelo.entidades;

public enum Especialidad {

    CARDIOLOGIA,
    DERMATOLOGIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    GERIATRIA,
    GINECOLOGIA,
    HEMATOLOGIA,
    INFECTOLOGIA,
    MEDICINA_DE_EMERGENCIA,
    MEDICINA_DEPORTIVA,
    MEDICINA_INTERNA,
    NEFROLOGIA,
    NEUMOLOGIA,
    NEUROLOGIA,
    OFTALMOLOGIA,
    ONCOLOGIA,
    ORTOPEDIA,
    OTORRINOLARINGOLOGIA,
    PEDIATRIA,
    PSIQUIATRIA,
    RADIOLOGIA,
    REUMATOLOGIA,
    TRAUMATOLOGIA,
    UROLOGIA;
}
